
spring:
  application:
    name:BufferBackend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/buffer
    username: root
    password: 12345678
  #失效时间
  session:
    timeout: 86400
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0